# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6a8e6828a17e94d7545e627578119cd27028ce58b930ef9c205389c394a2398f8c4cb2145258dcb7a60d9187efec85679735f3d112c20fe7bcc526c2ed9afc7

test:
  secret_key_base: 42a803437030d27ad9ed0060b71a62c0130ca9e62dcc378333ad8066fefc8cbfb4128660f50dff69037df821c88680f84e74f213ea96d2386b4da92ee7481c8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
